spring:
  datasource:
    url: jdbc:mysql://localhost:3306/analysis?characterEncoding=utf8
    username: root
    password: 123456
#    执行初始化脚本
#    schema: classpath:import.sql

mybatis:
    type-aliases-package: com.emrubik.analysis.domain
    mapper-locations: classpath:/com/emrubik/analysis/mapper/*.xml
    config-location: classpath:/mybatis-config.xml